name: Build and Deploy Pages

on:
   push:
      branches:
         - main
   # Allow running manually from the actions tab
   workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
   contents: read
   pages: write
   id-token: write

concurrency:
   group: "pages"
   cancel-in-progress: true

jobs:
   # Single deploy job since we're just deploying
   deploy:
      environment:
         name: github-pages
         url: ${{ steps.deployment.outputs.page_url }}

      runs-on: ubuntu-latest

      steps:
         -  name: Checkout
            uses: actions/checkout@master

         -  name: Set Deployed Flag and Image Root
            run: |
               bash ./.github/set-img-root.sh ${{ github.repository_owner }}

         - uses: DeLaGuardo/setup-clojure@12.5
           with:
             bb: latest
             github-token: ${{ secrets.GITHUB_TOKEN }}
         - name: Set updated time
           run: cat sns/meta-sns.json | jq "._meta.dateLastModified = $(date +'%s')" > sns/meta-sns.json
         - name: Generate merged homebrew JSON
           run: bb .github/generate-merged-json.bb
         - uses: actions/upload-artifact@v4
           with:
             name: sns.json
             path: homebrew/sns.json

         - name: Prepare SNS spells data
           run: cat homebrew/sns.json | jq -c '.spell' > data/spells/spells-sns.json

         - name: Prepare SNS bestiary data
           run: cat homebrew/sns.json | jq -c '.monster' > data/bestiary/bestiary-sns.json

         # Notably: remove anything which should not be added to the service worker manifest:
         #  - `homebrew`
         #  - `prerelease`
         -  name: Cleanup
            run: |
               rm -rf *.md *.zip scss spellcheck
               ls -lah

         # Remove entries from the `.gitignore` so the gh-pages action can correctly add+commit them to the pages branch
         -  name: Build Service Worker
            run: |
               node --version
               npm --version
               npm i
               npm run build:sw:prod
               sed -i 's/sw.js//g' .gitignore
               sed -i 's/sw-injector.js//g' .gitignore

         -  name: Build SEO Pages
            env:
               VET_SEO_IS_DEV_MODE: true
               VET_BASE_SITE_URL: "https://${{ github.repository_owner }}.github.io/"
               VET_SEO_IS_SKIP_UA_ETC: true
            run: |
               npm run build:seo -- ${{ github.ref_name }}

         -  name: Cleanup
            run: |
               rm -rf node_modules node
               ls -lah

         -  name: Setup Pages
            uses: actions/configure-pages@v5

         -  name: Upload artifact
            uses: actions/upload-pages-artifact@v3
            with:
              path: '.'

         -  name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
            with:
              # Timeout in millis (10 mins)
              timeout: 600000
